version: "3.3"
services:

  backend:
    env_file:
      - .env
    build:
      dockerfile: docker/backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
