version: "3.3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'befit'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'

  backend:
    env_file:
      - .env
    build:
      dockerfile: docker/backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db